In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Retail_Dataset_Modified.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [4]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring

In [5]:
print("Data Types:")
print(df.dtypes)

Data Types:
Store_ID                     str
Store_Name                   str
Brand_Name                   str
Store_Type                   str
City                         str
City_Tier                    str
Product_Name                 str
Category                     str
Sub_Category                 str
Product_Stage                str
Quantity_Available           str
Units_Sold                   str
Unit_Price                 int64
Cost_Price                 int64
Revenue                      str
Profit_Margin            float64
Average_Order_Value        int64
Inventory_Turnover       float64
Days_of_Stock              int64
Customer_Segment             str
Sales_Channel                str
Payment_Method               str
Supplier                     str
Supplier_Rating              str
Promotion_Type               str
Promotion_Impact         float64
Max_Discount_Offered       int64
Return_Rate              float64
Return_Reason                str
Customer_Satisfaction    float64
Online_Rating            float64
Review_Count               int64
Sales_Rep_Experience       int64
Sales_Rep_Rating         float64
Market_Share             float64
Competition_Level            str
Competitor_Count           int64
Brand_Loyalty            float64
Brand_Awareness          float64
Price_Competitiveness        str
Weather_Impact               str
Delivery_Time            float64
Shipping_Cost                str
Month                      int64
Year                       int64
Quarter                      str
Season                       str
dtype: object

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5171 non-null   str
 1   Store_Name             5171 non-null   str
 2   Brand_Name             5171 non-null   str
 3   Store_Type             5171 non-null   str
 4   City                   5109 non-null   str
 5   City_Tier              5171 non-null   str
 6   Product_Name           5098 non-null   str
 7   Category               5171 non-null   str
 8   Sub_Category           5171 non-null   str
 9   Product_Stage          5171 non-null   str
 10  Quantity_Available     5171 non-null   str
 11  Units_Sold             5171 non-null   str
 12  Unit_Price             5171 non-null   int64
 13  Cost_Price             5171 non-null   int64
 14  Revenue                5099 non-null   str
 15  Profit_Margin          5171 non-null   float64
 16  Average_Order_Value    5171 non-null   int64
 17  Inventory_Turnover     5171 non-null   float64
 18  Days_of_Stock          5171 non-null   int64
 19  Customer_Segment       5171 non-null   str
 20  Sales_Channel          5171 non-null   str
 21  Payment_Method         5171 non-null   str
 22  Supplier               5103 non-null   str
 23  Supplier_Rating        5171 non-null   str
 24  Promotion_Type         5171 non-null   str
 25  Promotion_Impact       5171 non-null   float64
 26  Max_Discount_Offered   5171 non-null   int64
 27  Return_Rate            5171 non-null   float64
 28  Return_Reason          5171 non-null   str
 29  Customer_Satisfaction  5094 non-null   float64
 30  Online_Rating          5171 non-null   float64
 31  Review_Count           5171 non-null   int64
 32  Sales_Rep_Experience   5171 non-null   int64
 33  Sales_Rep_Rating       5171 non-null   float64
 34  Market_Share           5171 non-null   float64
 35  Competition_Level      5171 non-null   str
 36  Competitor_Count       5171 non-null   int64
 37  Brand_Loyalty          5171 non-null   float64
 38  Brand_Awareness        5171 non-null   float64
 39  Price_Competitiveness  5171 non-null   str
 40  Weather_Impact         5171 non-null   str
 41  Delivery_Time          5111 non-null   float64
 42  Shipping_Cost          5171 non-null   str
 43  Month                  5171 non-null   int64
 44  Year                   5171 non-null   int64
 45  Quarter                5171 non-null   str
 46  Season                 5171 non-null   str
dtypes: float64(11), int64(10), str(26)
memory usage: 1.9 MB

In [7]:
df['Quantity_Available'] = pd.to_numeric(df['Quantity_Available'], errors='coerce')

In [8]:
print(df['Quantity_Available'].dtypes)

float64

In [9]:
df['Units_Sold'] = pd.to_numeric(df['Units_Sold'], errors='coerce')

In [10]:
print(df['Units_Sold'].dtypes)

float64

In [11]:
df['Shipping_Cost'] = pd.to_numeric(df['Shipping_Cost'], errors='coerce')
print(df['Shipping_Cost'].dtypes)

float64

In [12]:
print(df[['Quantity_Available', 'Units_Sold', 'Revenue', 'Shipping_Cost']].dtypes)

Quantity_Available    float64
Units_Sold            float64
Revenue                   str
Shipping_Cost         float64
dtype: object

In [13]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Store_ID                  0
Store_Name                0
Brand_Name                0
Store_Type                0
City                     62
City_Tier                 0
Product_Name             73
Category                  0
Sub_Category              0
Product_Stage             0
Quantity_Available        8
Units_Sold                8
Unit_Price                0
Cost_Price                0
Revenue                  72
Profit_Margin             0
Average_Order_Value       0
Inventory_Turnover        0
Days_of_Stock             0
Customer_Segment          0
Sales_Channel             0
Payment_Method            0
Supplier                 68
Supplier_Rating           0
Promotion_Type            0
Promotion_Impact          0
Max_Discount_Offered      0
Return_Rate               0
Return_Reason             0
Customer_Satisfaction    77
Online_Rating             0
Review_Count              0
Sales_Rep_Experience      0
Sales_Rep_Rating          0
Market_Share              0
Competition_Level         0
Competitor_Count          0
Brand_Loyalty             0
Brand_Awareness           0
Price_Competitiveness     0
Weather_Impact            0
Delivery_Time            60
Shipping_Cost             8
Month                     0
Year                      0
Quarter                   0
Season                    0
dtype: int64

In [14]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Store_ID                  0
Store_Name                0
Brand_Name                0
Store_Type                0
City                     62
City_Tier                 0
Product_Name             73
Category                  0
Sub_Category              0
Product_Stage             0
Quantity_Available        8
Units_Sold                8
Unit_Price                0
Cost_Price                0
Revenue                  72
Profit_Margin             0
Average_Order_Value       0
Inventory_Turnover        0
Days_of_Stock             0
Customer_Segment          0
Sales_Channel             0
Payment_Method            0
Supplier                 68
Supplier_Rating           0
Promotion_Type            0
Promotion_Impact          0
Max_Discount_Offered      0
Return_Rate               0
Return_Reason             0
Customer_Satisfaction    77
Online_Rating             0
Review_Count              0
Sales_Rep_Experience      0
Sales_Rep_Rating          0
Market_Share              0
Competition_Level         0
Competitor_Count          0
Brand_Loyalty             0
Brand_Awareness           0
Price_Competitiveness     0
Weather_Impact            0
Delivery_Time            60
Shipping_Cost             8
Month                     0
Year                      0
Quarter                   0
Season                    0
dtype: int64

In [15]:
missing_cols = df.isnull().sum()
print(
    missing_cols[missing_cols > 0]
)

City                     62
Product_Name             73
Quantity_Available        8
Units_Sold                8
Revenue                  72
Supplier                 68
Customer_Satisfaction    77
Delivery_Time            60
Shipping_Cost             8
dtype: int64

In [16]:
df[('City')].fillna(df['City'].mode()[0], inplace=True)

C:\Users\rohit\AppData\Local\Temp\ipykernel_23228\252043348.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[('City')].fillna(df['City'].mode()[0], inplace=True)

0          Pune
1        Mumbai
2          Pune
3       Chennai
4       Chennai
         ...
5166    Jaipur
5167    Mumbai
5168    Kanpur
5169    Mumbai
5170     Delhi
Name: City, Length: 5171, dtype: str

In [17]:
df['Product_Name'].fillna(
    df['Product_Name'].mode()[0],
    inplace=True
)

C:\Users\rohit\AppData\Local\Temp\ipykernel_23228\519652800.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Product_Name'].fillna(

0        Green Tea 100g
1       White Sugar 1kg
2        Levi's T-Shirt
3         Adidas Hoodie
4         PlayStation 5
             ...
5166         Pepe Jeans
5167    White Sugar 1kg
5168        Dell XPS 13
5169       Nike Air Max
5170     MacBook Air M2
Name: Product_Name, Length: 5171, dtype: str

In [18]:
duplicates = df.duplicated().sum()

print(
    "Duplicate Records:",
    duplicates
)

Duplicate Records: 25

In [19]:
print(df.duplicated().value_counts())

False    5146
True       25
Name: count, dtype: int64

In [20]:
df = df.drop_duplicates()

In [21]:
print(df.shape)

(5146, 47)

In [22]:
print(
    "Remaining Duplicates:",
    df.duplicated().sum()
)

Remaining Duplicates: 0

In [23]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring