# pandas

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("Retail_Dataset_Modified.csv")

In [6]:
df.head(15)

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
5,BX_DELHI_082,BrandX_India Superstore Delhi,BrandX_India,Street Store,Delhi,Metro,Toor Dal 1kg,Groceries,Dal,New Launch,...,81.3,85.3,Aggressive,Low,4.0,108,1,2022,Q1,Spring
6,BX_MUMBAI_062,BrandX_India Accessories Mumbai,BrandX_India,Street Store,Mumbai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Mature,...,98.0,81.6,Competitive,Low,2.0,90,1,2022,Q1,Spring
7,BX_DELHI_062,BrandX_India Digital Delhi,BrandX_India,Mall Store,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Mature,...,81.6,82.4,Competitive,Low,3.0,137,1,2022,Q1,Spring
8,BX_MUMBAI_042,BrandX_India Appliances Mumbai,BrandX_India,Street Store,Mumbai,Metro,NaN,Home Appliances,Water Purifiers,Declining,...,96.3,82.7,Aggressive,Low,4.0,214,1,2022,Q1,Spring
9,BX_NAGPUR_077,BrandX_India Style Nagpur,BrandX_India,Mall Store,Nagpur,Tier2,H&M Cotton Tee,Clothes,T-Shirts,New Launch,...,69.6,64.6,Standard,Medium,3.0,73,1,2022,Q1,Spring
10,BX_MUMBAI_094,BrandX_India Trends Mumbai,BrandX_India,Mall Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,New Launch,...,78.8,81.5,Aggressive,Medium,3.0,52,1,2022,Q1,Spring
11,BX_DELHI_088,BrandX_India Superstore Delhi,BrandX_India,Street Store,Delhi,Metro,Olive Oil 500ml,Groceries,Oil,Discontinued,...,81.6,85.9,Competitive,Low,4.0,73,1,2022,Q1,Spring
12,BX_DELHI_082,BrandX_India Gadget Zone Delhi,BrandX_India,Street Store,Delhi,Metro,Samsung Galaxy S23,Electronics,Smartphones,New Launch,...,78.4,87.2,Competitive,Low,1.0,146,1,2022,Q1,Spring
13,BX_DELHI_005,BrandX_India Electronics Delhi,BrandX_India,Express,Delhi,Metro,AirPods Pro,Electronics,Headphones,Growing,...,75.2,87.7,Competitive,Low,4.0,244,1,2022,Q1,Spring
14,BX_NAGPUR_094,BrandX_India Fashion Nagpur,BrandX_India,Street Store,Nagpur,Tier2,Levi's 511 Jeans,Clothes,Jeans,Discontinued,...,72.2,68.3,Standard,Medium,2.0,97,1,2022,Q1,Spring

In [7]:
df.tail()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [8]:
list1 = [1,2,3]
list2 = [4,5,6]
print(list1 + list2)
# Output [1, 2, 3, 4, 5, 6] --> lists just joined (concatenated), no addition!

[1, 2, 3, 4, 5, 6]

In [9]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)

[5 7 9]

In [10]:
print("Dataset Shape:")
print(df.shape)

Dataset Shape:
(5171, 47)

In [11]:
print("Columns:")
print(df.columns)

Columns:
Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='str')

In [12]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5171 non-null   str
 1   Store_Name             5171 non-null   str
 2   Brand_Name             5171 non-null   str
 3   Store_Type             5171 non-null   str
 4   City                   5109 non-null   str
 5   City_Tier              5171 non-null   str
 6   Product_Name           5098 non-null   str
 7   Category               5171 non-null   str
 8   Sub_Category           5171 non-null   str
 9   Product_Stage          5171 non-null   str
 10  Quantity_Available     5171 non-null   str
 11  Units_Sold             5171 non-null   str
 12  Unit_Price             5171 non-null   int64
 13  Cost_Price             5171 non-null   int64
 14  Revenue                5099 non-null   str
 15  Profit_Margin          5171 non-null   float64
 16  Average_Order_Value    5171 non-null   int64
 17  Inventory_Turnover     5171 non-null   float64
 18  Days_of_Stock          5171 non-null   int64
 19  Customer_Segment       5171 non-null   str
 20  Sales_Channel          5171 non-null   str
 21  Payment_Method         5171 non-null   str
 22  Supplier               5103 non-null   str
 23  Supplier_Rating        5171 non-null   str
 24  Promotion_Type         5171 non-null   str
 25  Promotion_Impact       5171 non-null   float64
 26  Max_Discount_Offered   5171 non-null   int64
 27  Return_Rate            5171 non-null   float64
 28  Return_Reason          5171 non-null   str
 29  Customer_Satisfaction  5094 non-null   float64
 30  Online_Rating          5171 non-null   float64
 31  Review_Count           5171 non-null   int64
 32  Sales_Rep_Experience   5171 non-null   int64
 33  Sales_Rep_Rating       5171 non-null   float64
 34  Market_Share           5171 non-null   float64
 35  Competition_Level      5171 non-null   str
 36  Competitor_Count       5171 non-null   int64
 37  Brand_Loyalty          5171 non-null   float64
 38  Brand_Awareness        5171 non-null   float64
 39  Price_Competitiveness  5171 non-null   str
 40  Weather_Impact         5171 non-null   str
 41  Delivery_Time          5111 non-null   float64
 42  Shipping_Cost          5171 non-null   str
 43  Month                  5171 non-null   int64
 44  Year                   5171 non-null   int64
 45  Quarter                5171 non-null   str
 46  Season                 5171 non-null   str
dtypes: float64(11), int64(10), str(26)
memory usage: 1.9 MB
None

In [13]:
print(df.columns)

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='str')

In [14]:
import numpy as np

In [15]:
storename_array = np.array(df["Store_Name"])

print(storename_array)

['BrandX_India Superstore Pune' 'BrandX_India Superstore Mumbai'
 'BrandX_India Trends Pune' ... 'BrandX_India Gadget Zone Kanpur'
 'BrandX_India Style Mumbai' 'BrandX_India Electronics Delhi']

In [16]:
print("First storename Value:")
print(storename_array[0])

First storename Value:
BrandX_India Superstore Pune

In [17]:
print("Store Names from Index 10 to 20:")
print(storename_array[10:21])

Store Names from Index 10 to 20:
['BrandX_India Trends Mumbai' 'BrandX_India Superstore Delhi'
 'BrandX_India Gadget Zone Delhi' 'BrandX_India Electronics Delhi'
 'BrandX_India Fashion Nagpur' 'BrandX_India Appliances Bangalore'
 'BrandX_India Style Delhi' 'BrandX_India Daily Bangalore'
 'BrandX_India Comfort Hyderabad' 'BrandX_India Style Mumbai'
 'BrandX_India Digital Delhi']